import { InventoryItem, StockMovement } from "../types/inventory";

// Mock inventory data
export const mockInventoryItems: InventoryItem[] = [
  {
    id: "med-001",
    name: "Paracetamol 500mg",
    category: "Medicine",
    quantity: 250,
    unit: "tablet",
    expirationDate: new Date(2025, 5, 15),
    reorderThreshold: 50,
    lastUpdated: new Date(2023, 10, 5),
    isVaccine: false,
  },
  {
    id: "med-002",
    name: "Amoxicillin 250mg",
    category: "Medicine",
    quantity: 120,
    unit: "capsule",
    expirationDate: new Date(2024, 8, 30),
    reorderThreshold: 30,
    lastUpdated: new Date(2023, 11, 10),
    isVaccine: false,
  },
  {
    id: "vac-001",
    name: "COVID-19 Vaccine",
    category: "Vaccine",
    quantity: 45,
    unit: "vial",
    expirationDate: new Date(2024, 3, 15),
    batchNumber: "COV-2023-11",
    lotNumber: "L789456",
    reorderThreshold: 10,
    location: "Refrigerator 2",
    lastUpdated: new Date(2023, 12, 1),
    isVaccine: true,
  },
  {
    id: "sup-001",
    name: "Disposable Syringes 5ml",
    category: "Supply",
    quantity: 500,
    unit: "piece",
    expirationDate: null,
    reorderThreshold: 100,
    lastUpdated: new Date(2023, 9, 20),
    isVaccine: false,
  },
  {
    id: "sup-002",
    name: "Surgical Masks",
    category: "Supply",
    quantity: 35,
    unit: "box",
    expirationDate: null,
    reorderThreshold: 20,
    lastUpdated: new Date(2023, 11, 25),
    isVaccine: false,
  },
  {
    id: "eqp-001",
    name: "Digital Thermometer",
    category: "Equipment",
    quantity: 8,
    unit: "piece",
    expirationDate: null,
    reorderThreshold: 3,
    lastUpdated: new Date(2023, 8, 15),
    isVaccine: false,
  },
  {
    id: "vac-002",
    name: "Influenza Vaccine",
    category: "Vaccine",
    quantity: 15,
    unit: "vial",
    expirationDate: new Date(2024, 1, 30),
    batchNumber: "INF-2023-05",
    lotNumber: "L123789",
    reorderThreshold: 10,
    location: "Refrigerator 1",
    lastUpdated: new Date(2023, 11, 5),
    isVaccine: true,
  },
  {
    id: "med-003",
    name: "Ibuprofen 400mg",
    category: "Medicine",
    quantity: 180,
    unit: "tablet",
    expirationDate: new Date(2025, 2, 10),
    reorderThreshold: 40,
    lastUpdated: new Date(2023, 10, 15),
    isVaccine: false,
  },
];

// Mock stock movement data
export const mockStockMovements: StockMovement[] = [
  {
    id: "mov-001",
    itemId: "med-001",
    type: "incoming",
    quantity: 100,
    date: new Date(2023, 10, 5),
    performedBy: "Dr. Santos",
  },
  {
    id: "mov-002",
    itemId: "med-001",
    type: "outgoing",
    quantity: 25,
    date: new Date(2023, 10, 10),
    reason: "Patient dispensing",
    performedBy: "Nurse Reyes",
  },
  {
    id: "mov-003",
    itemId: "vac-001",
    type: "incoming",
    quantity: 50,
    date: new Date(2023, 12, 1),
    batchNumber: "COV-2023-11",
    lotNumber: "L789456",
    performedBy: "Dr. Mendoza",
  },
  {
    id: "mov-004",
    itemId: "vac-001",
    type: "outgoing",
    quantity: 5,
    date: new Date(2023, 12, 5),
    batchNumber: "COV-2023-11",
    lotNumber: "L789456",
    reason: "Vaccination program",
    performedBy: "Nurse Garcia",
  },
];
